import React from 'react'
import { graphql, useStaticQuery } from 'gatsby'
import { Button } from '../shared'
import { Route } from '../../constants/routes'
import { ProjectPreview } from '../ProjectPreview'
import { IProjectPreview } from '../../types'
